---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MSI.
--- DateTime: 14.07.2022 22:39
---
do

    local InitGlobalsOrigin = InitGlobals



	function InitGlobals()
        InitGlobalsOrigin()

        GetUnitX = GetUnitRealX
        GetUnitY = GetUnitRealY

        local func_id = 0
        local init_que = { InitLocaleLibrary, UnitDataInit, MainEngineInit }

            for i = 1, #init_que do
                init_que[i]()
                print(init_que[i])
            end

            DoNotSaveReplay()
            AirPathingUnit = CreateUnit(Player(PLAYER_NEUTRAL_PASSIVE), FourCC("hgry"), 0.,0., 0.)
            ShowUnit(AirPathingUnit, false)
            GroundPathingItem = CreateItem(FourCC("rde2"), 0.,0.)
            SetItemVisible(GroundPathingItem, false)

    end



end