---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MSI.
--- DateTime: 14.07.2022 22:59
---
do




    function OnUnitCreated(new_unit)
        local unit_data = GetUnitData(new_unit)



    end


    function OnUnitDeath(unit, killer)

        if killer then

        end

    end


    function OnUnitEffectApply(unit, effect_id)

    end

    function OnUnitEffectEnd(unit, effect_id)

    end


    function OnChargeEnd(source, targets_hit, sign, negative_state)


    end


    function OnChargeHit(source, target, sign)

        return false
    end


    function OnJumpExpire(target, sign)

    end


    function OnPullRelease(source, target, sign)

    end


    function OnPushExpire(target, data)

    end


    ---@param source unit
    ---@param missile table
    function OnMissileImpact(source, missile)

    end

    ---@param source unit
    ---@param target unit
    ---@param missile table
    function OnMissileExpire(source, target, missile)

    end

    ---@param source unit
    ---@param target unit
    ---@param missile table
    function OnMissileHit(source, target, missile)

    end


    ---@param missile table
    ---@param source unit
    ---@param target unit
    function OnMissileLaunch(source, target, missile)


    end




    ---@param source unit
    ---@param target unit
    ---@param damage_data table
    ---@param damage real
    function OnDamage_End(source, target, damage, damage_data)

    end

    ---@param source unit
    ---@param damage table
    function OnDamage_PreHit(source, target, damage, damage_data)

    end


    function OnDamageStart(source, target, damage_data)


        return damage_data
    end




    ---@param source unit
    ---@param target unit
    function OnAttackEnd(source, target)

    end

    ---@param source unit
    ---@param target unit
    function OnMyAttack(source, target, attack_data)

        return attack_data
    end

    ---@param source unit
    ---@param target unit
    ---@return table
    function OnAttackStart(source, target, attack_data)

        return attack_data
    end


    ---@param source unit
    ---@param target unit
    ---@param point_x real
    ---@param point_y real
    ---@param action_id string
    function OnActionEnd(source, target, point_x, point_y, action_id)

    end


    ---@param source unit
    ---@param victim unit
    ---@param additional_data table
    ---@return table
    function OnAction(source, victim, additional_data)


        return additional_data
    end


    ---@param source unit
    ---@param target unit
    ---@param skill table
    ---@param x real
    ---@param y real
    function OnSkillCastEnd(source, target, x, y, skill, ability_level)

    end


    ---@param source unit
    ---@param target unit
    ---@param x real
    ---@param y real
    ---@param skill table
    function OnSkillCast(source, target, x, y, skill, ability_level)


    end


    ---@param source unit
    ---@param target unit
    ---@param skill table
    ---@param level integer
    ---@param skill_data table
    function OnSkillPrecast(source, target, skill, level, skill_data)

    end



end



