---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MSI.
--- DateTime: 14.07.2022 22:51
---
do

    UnitsData       = 0
    UnitsList       = 0


    ---@param source unit function
    function GetUnitData(source)
        return UnitsList[GetHandleId(source)]
    end

    ---@param effect string
    ---@param unit unit
    ---@return boolean
    function UnitHasEffect(unit, effect)
        local unit_data = GetUnitData(unit)
        return unit_data.effects[effect]
    end

    ---@param effect string
    ---@param unit unit
    function UnitAddEffect(unit, effect)
        local unit_data = GetUnitData(unit)

            if unit_data.effects[effect] then unit_data.effects[effect] = unit_data.effects[effect] + 1
            else unit_data.effects[effect] = 1 end

            OnUnitEffectApply(unit, effect)

    end

    ---@param effect string
    ---@param unit unit
    function UnitRemoveEffect(unit, effect)
        local unit_data = GetUnitData(unit)

            if unit_data.effects[effect] then
                unit_data.effects[effect] = unit_data.effects[effect] - 1
                if unit_data.effects[effect] <= 0 then
                    unit_data.effects[effect] = nil
                    OnUnitEffectEnd(unit, effect)
                end
            end

    end



    ---@param source unit
    ---@param reference_data table
    function NewUnitByTemplate(source, reference_data)
        local data  = MergeTables({}, reference_data)

            data.Owner = source
            data.action_timer = CreateTimer()
            UnitsList[GetHandleId(source)] = data

        return data
    end


    function NewUnitTemplate(id, reference)
        local new_data = { }

            MergeTables(new_data, reference)

        UnitsData[FourCC(id)] = new_data
    end




    function InitUnitsDataOnMap()
        local group = CreateGroup()

            GroupEnumUnitsInRect(group, bj_mapInitialPlayableArea, nil)

                ForGroup(group, function ()
                    local handle = GetUnitTypeId(GetEnumUnit())

                        if UnitsData[handle] then
                            NewUnitByTemplate(GetEnumUnit(), UnitsData[handle])
                            if UnitsData[handle].name then BlzSetUnitName(GetEnumUnit(), UnitsData[handle].name) end
                            OnUnitCreated(GetEnumUnit())
                        end

                end)

        DestroyGroup(group)
    end






    function UnitDataInit()

        UnitsData       = { }
        UnitsList       = { }



        NewUnitTemplate("trsv", {
            name = GetLocalString("К.С.М.", "S.C.V."),
            death_sound = { pack = { "Sound\\SCV\\tscdth00.wav" }, volume = 110, cutoff = 1700. },
            time_before_remove = 10.
        })

        NewUnitTemplate("trmr", {
            name = GetLocalString("Морпех", "Marine"),
            weapon = {
                {
                    damage = 6,
                    damage_type = DAMAGE_TYPE_STANDARD,
                    --impact_sound = { pack = { "Sound\\Marine\\tmafir00.wav" }, volume = 115, cutoff = 1700. }
                },
            },
            death_sound = { pack = { "Sound\\Marine\\tmadth00.wav", "Sound\\Marine\\tmadth01.wav" }, volume = 110, cutoff = 1700. },
            time_before_remove = 10.
        })


        NewUnitTemplate("trfb", {
            name = GetLocalString("Огнеметчик", "Firebat"),
            weapon = {
                {
                    damage = 8,
                    damage_type = DAMAGE_TYPE_CONCUSSIVE,
                    custom_attack = true
                },
            },
            fire_sound = { pack = { "Sound\\Firebat\\tfbfir00.wav", "Sound\\Firebat\\tfbfir01.wav" }, volume = 120, cutoff = 1900., distance = 3500. },
            death_sound = { pack = { "Sound\\Firebat\\tfbdth00.wav", "Sound\\Firebat\\tfbdth01.wav", "Sound\\Firebat\\tfbdth02.wav" }, volume = 110, cutoff = 1700. },
            time_before_remove = 10.
        })


        NewUnitTemplate("trgh", {
            name = GetLocalString("Призрак", "Ghost"),
            weapon = {
                {
                    damage = 10,
                    damage_type = DAMAGE_TYPE_CONCUSSIVE,
                },
            },
            death_sound = { pack = { "Sound\\Ghost\\tghdth00.wav", "Sound\\Ghost\\tghdth01.wav" }, volume = 110, cutoff = 1700. },
            time_before_remove = 10.
        })

        NewUnitTemplate("trmd", {
            name = GetLocalString("Медик", "Medic"),
            death_sound = { pack = { "Sound\\Medic\\TMdDth00.wav" }, volume = 110, cutoff = 1700. },
            time_before_remove = 10.
        })

        NewUnitTemplate("trvl", {
            name = GetLocalString("Стервятник", "Vulture"),
            weapon = {
                {
                    damage = 20,
                    damage_type = DAMAGE_TYPE_CONCUSSIVE,
                    impact_sound = { pack = { "Sound\\Vulture\\tvuhit00.wav", "Sound\\Vulture\\tvuhit01.wav", "Sound\\Vulture\\tvuhit02.wav"  }, volume = 110, cutoff = 1700. }
                },
            },
            death_sound = { pack = { "Sound\\Vulture\\tvudth00.wav" }, volume = 110, cutoff = 1700. },
            time_before_remove = 10.
        })

        NewUnitTemplate("trgf", {
            name = GetLocalString("Голиаф", "Goliath"),
            weapon = {
                {
                    damage = 12,
                    damage_type = DAMAGE_TYPE_STANDARD,
                    --impact_sound = { pack = { "Sound\\Vulture\\tvuhit00.wav", "Sound\\Vulture\\tvuhit01.wav", "Sound\\Vulture\\tvuhit02.wav"  }, volume = 110, cutoff = 1700. }
                },
                {
                    damage = 10,
                    damage_type = DAMAGE_TYPE_EXPLOSIVE,
                    amount = 2,
                    impact_sound = { pack = { "Sound\\Misc\\explo2.wav" }, volume = 95, cutoff = 1700. }
                },
            },
            death_sound = { pack = { "Sound\\Goliath\\tgodth00.wav" }, volume = 110, cutoff = 1700. },
            time_before_remove = 10.
        })


        NewUnitTemplate("trst", {
            name = GetLocalString("Осадный Танк", "Siege Tank"),
            weapon = {
                {
                    damage = 30,
                    damage_type = DAMAGE_TYPE_EXPLOSIVE,
                },
                {
                    damage = 70,
                    damage_type = DAMAGE_TYPE_EXPLOSIVE,
                    inner_range = 23.475,
                    medium_range = 58.575,
                    outer_range = 93.75,
                    target_types = { UNIT_TYPE_GROUND },
                    target_friendly = true,
                    impact_sound = { pack = { "Sound\\Misc\\explolrg.wav" }, volume = 95, cutoff = 1700. },
                    impact_effect = { path = "Effect\\siege mode impact.mdx", random_angle = true }
                },
            },
            death_sound = { pack = { "Sound\\SiegeTank\\ttadth00.wav" }, volume = 110, cutoff = 1700. },
            time_before_remove = 10.
        })

        NewUnitTemplate("trwr", {
            name = GetLocalString("Мираж", "Wraith"),
            weapon = {
                {
                    damage = 8,
                    damage_type = DAMAGE_TYPE_EXPLOSIVE,
                },
                {
                    damage = 20,
                    damage_type = DAMAGE_TYPE_EXPLOSIVE,
                    impact_sound = { pack = { "Sound\\Misc\\explosm.wav" }, volume = 95, cutoff = 1700. }
                },
            },
            death_sound = { pack = { "Sound\\Wraith\\tphdth00.wav" }, volume = 110, cutoff = 1700. },
            time_before_remove = 10.
        })

        NewUnitTemplate("trds", {
            name = GetLocalString("Десантный Корабль", "Dropship"),
            death_sound = { pack = { "Sound\\Dropship\\tdrdth00.wav" }, volume = 110, cutoff = 1700. },
            time_before_remove = 10.
        })

        NewUnitTemplate("trss", {
            name = GetLocalString("Научное Судно", "Science Vessel"),
            death_sound = { pack = { "Sound\\ScienceVessel\\tvedth00.wav" }, volume = 110, cutoff = 1700. },
            time_before_remove = 10.
        })

        NewUnitTemplate("trvc", {
            name = GetLocalString("Валькирья", "Valkyrie"),
            weapon = {
                {
                    damage = 6,
                    damage_type = DAMAGE_TYPE_EXPLOSIVE,
                    custom_attack = true,
                    --impact_sound = { pack = { "Sound\\Valkyrie\\Tfrhit.wav" }, volume = 110, cutoff = 1700. }
                },
            },
            death_sound = { pack = { "Sound\\Valkyrie\\TVkDth00.wav" }, volume = 110, cutoff = 1700. },
            time_before_remove = 10.
        })

        NewUnitTemplate("trbc", {
            name = GetLocalString("Крейсер", "Battlecruiser"),
            weapon = {
                {
                    damage = 25,
                    damage_type = DAMAGE_TYPE_STANDARD,
                },
            },
            missile_eject_range = 85.,
            missile_eject_z = -15.,
            death_sound = { pack = { "Sound\\Battlecruiser\\tbadth00.wav" }, volume = 110, cutoff = 1700. },
            time_before_remove = 10.
        })


        NewUnitTemplate("trs1", {
            name = GetLocalString("Паучья Мина", "Spider Mine"),
            weapon = {
                {
                    damage = 125,
                    damage_type = DAMAGE_TYPE_EXPLOSIVE,
                    custom_attack = true
                },
            },
            death_sound = { pack = { "Sound\\Misc\\explo1.wav" }, volume = 110, cutoff = 1700. },
            time_before_remove = 10.
        })

        NewUnitTemplate("trcc", {
            name = GetLocalString("Командный Центр", "Command Center"),
            death_sound = { pack = { "Sound\\Misc\\explo4.wav" }, volume = 110, cutoff = 1700. },
            alternate_model = FourCC("h001"),
            liftoff_animation = 1,
            land_animation = 3,
            time_before_remove = 10.
        })

        NewUnitTemplate("trbr", {
            name = GetLocalString("Бараки", "Barracks"),
            death_sound = { pack = { "Sound\\Misc\\explo4.wav" }, volume = 110, cutoff = 1700. },
            alternate_model = FourCC("trbr"),
            liftoff_animation = 3,
            land_animation = 4,
            time_before_remove = 10.
        })

        NewUnitTemplate("treb", {
            name = GetLocalString("Инженерный Комплекс", "Engineering Bay"),
            death_sound = { pack = { "Sound\\Misc\\explo4.wav" }, volume = 110, cutoff = 1700. },
            alternate_model = FourCC("h002"),
            liftoff_animation = 1,
            land_animation = 3,
            time_before_remove = 10.
        })

        NewUnitTemplate("trsp", {
            name = GetLocalString("Космопорт", "Starport"),
            death_sound = { pack = { "Sound\\Misc\\explo4.wav" }, volume = 110, cutoff = 1700. },
            alternate_model = FourCC("h003"),
            liftoff_animation = 1,
            land_animation = 3,
            time_before_remove = 10.
        })

        NewUnitTemplate("trfc", {
            name = GetLocalString("Завод", "Factory"),
            death_sound = { pack = { "Sound\\Misc\\explo4.wav" }, volume = 110, cutoff = 1700. },
            alternate_model = FourCC("h004"),
            liftoff_animation = 1,
            land_animation = 3,
            time_before_remove = 10.
        })

        NewUnitTemplate("trmt", {
            name = GetLocalString("Ракетная турель", "Missile Turret"),
            weapon = {
                {
                    damage = 20,
                    damage_type = DAMAGE_TYPE_EXPLOSIVE
                },
            },
            death_sound = { pack = { "Sound\\Misc\\explo4.wav" }, volume = 110, cutoff = 1700. },
            time_before_remove = 10.
        })

        NewUnitTemplate("trsf", {
            name = GetLocalString("Научный Комплекс", "Science Facility"),
            death_sound = { pack = { "Sound\\Misc\\explo4.wav" }, volume = 110, cutoff = 1700. },
            alternate_model = FourCC("h005"),
            liftoff_animation = 1,
            land_animation = 3,
            time_before_remove = 10.
        })

        NewUnitTemplate("trsd", {
            name = GetLocalString("Хранилище", "Supply Depot"),
            death_sound = { pack = { "Sound\\Misc\\explo4.wav" }, volume = 110, cutoff = 1700. },
            time_before_remove = 10.
        })

        NewUnitTemplate("trsd", {
            name = GetLocalString("Хранилище", "Supply Depot"),
            death_sound = { pack = { "Sound\\Misc\\explo4.wav" }, volume = 110, cutoff = 1700. },
            time_before_remove = 10.
        })

        NewUnitTemplate("trrf", {
            name = GetLocalString("Перерабатывающий Завод", "Refinery"),
            death_sound = { pack = { "Sound\\Misc\\explo4.wav" }, volume = 110, cutoff = 1700. },
            time_before_remove = 10.
        })

        NewUnitTemplate("tram", {
            name = GetLocalString("Оружейная", "Armory"),
            death_sound = { pack = { "Sound\\Misc\\explo4.wav" }, volume = 110, cutoff = 1700. },
            time_before_remove = 10.
        })

        NewUnitTemplate("trbn", {
            name = GetLocalString("Бункер", "Bunker"),
            death_sound = { pack = { "Sound\\Misc\\explo4.wav" }, volume = 110, cutoff = 1700. },
            time_before_remove = 10.
        })


        --BlzSetAbilityStringField(ab, ABILITY_SF_ICON_ACTIVATED)
        local trg = CreateTrigger()
        TriggerRegisterEnterRectSimple(trg, bj_mapInitialPlayableArea)
        TriggerAddAction(trg, function ()

            local unit = GetTriggerUnit()

                if UnitsList[GetHandleId(unit)] == nil and UnitsData[GetUnitTypeId(unit)] then
                    NewUnitByTemplate(unit, UnitsData[GetUnitTypeId(unit)])
                    if UnitsData[GetUnitTypeId(unit)].name then BlzSetUnitName(unit, UnitsData[GetUnitTypeId(unit)].name) end
                    OnUnitCreated(unit)
                end

        end)

        trg = CreateTrigger()
        TriggerRegisterAnyUnitEventBJ(trg, EVENT_PLAYER_UNIT_DEATH)
        TriggerAddAction(trg, function ()
            local unit_data = GetUnitData(GetTriggerUnit())

                if unit_data then
                    --TimerStart(unit_data.action_timer, 0., false, nil)
                    --TimerStart(unit_data.attack_timer, 0., false, nil)

                    if unit_data.death_sound then
                        AddSoundVolume(unit_data.death_sound.pack[GetRandomInt(1, #unit_data.death_sound.pack)], GetUnitX(unit_data.Owner), GetUnitY(unit_data.Owner), unit_data.death_sound.volume, unit_data.death_sound.cutoff)
                    end

                    if unit_data.hide_body then
                        DelayAction(unit_data.base_stats.death_time, function() ShowUnit(unit_data.Owner) end)
                    end

                    if unit_data.time_before_remove > 0. then
                        local handle = GetHandleId(unit_data.Owner)

                            local timer = CreateTimer()
                            TimerStart(timer, unit_data.time_before_remove, false, function()
                                DestroyTimer(unit_data.action_timer)
                                --DestroyTimer(unit_data.attack_timer)
                                UnitsList[handle] = nil
                                DestroyTimer(timer)
                            end)

                    end

                end

                OnUnitDeath(GetTriggerUnit(), GetKillingUnit())

        end)

        InitUnitsDataOnMap()

        Cheat("greedisgood")
        Cheat("warpten")

        local building_trigger = CreateTrigger()
        TriggerRegisterAnyUnitEventBJ(building_trigger, EVENT_PLAYER_UNIT_CONSTRUCT_FINISH)
        TriggerAddAction(building_trigger, function()
            if GetUnitTypeId(GetTriggerUnit()) == FourCC("trbn") then
                BunkerBuilt(GetTriggerUnit())
            end
        end)


        local load_trigger = CreateTrigger()

            TriggerRegisterAnyUnitEventBJ(load_trigger, EVENT_PLAYER_UNIT_LOADED)
            --TriggerRegisterUnitEvent(load_trigger, unit, EVENT_UNIT_LOADED)
            TriggerAddAction(load_trigger, function()
                local cargo_type = GetUnitTypeId(GetTransportUnit())

                    if cargo_type == FourCC("trbn") then
                        BunkerLoadUnit(GetTransportUnit(), GetTriggerUnit())
                    end
            end)

    end

end